### PR TITLE
Add EWS

### LINKED ISSUE #79: Add EWS (Embedded Web Server)
Adding the issue so that I do not forget about creating a pull request.

Add [EWS](http://embed-web-srvr.sourceforge.net/) from Simon Wright.

### PR DESCRIPTION
**Pull request by Irvise**
Closes #79

### CODE REVIEW

**Comment by onox** [comment]
Would it be possible for @simonjwright to move the project to GitHub or does he want it to keep it at SF? (SF is just aweful and a thing from the past IMO)

**Comment by simonjwright** [comment]
Moved https://github.com/simonjwright/ews from SF. Some work needed, I think, unless https://github.com/simonjwright/ews/blob/master/doc/ews.pdf would do ... oh, no, it’s not a live view, will have to do something. Also, that’s not a README, it’s a release history!

**Comment by Irvise** [comment]
Thank you @simonjwright I will update this PR once you give me the thumbs up :)

**Comment by simonjwright** [comment]
OK to go ahead.

**Pull request merged**
