### PR TITLE
Add ASFML to Games section

### PR DESCRIPTION
**Pull request by mgrojo**

### CODE REVIEW

**Comment by onox** [comment]
I think it would be more appropriate to add it to the https://github.com/ohenley/awesome-ada#computer-graphics section, which is where you'll find bindings for GLFW and SDL as well.

**Comment by mgrojo** [comment]
But SFML also includes audio, network and other interfaces. I looked for a multimedia section, but it's only under 'Applications'.  Maybe the scope o that section should be extended to 'Graphics & Multimedia'? In that regard, SDL is similar.

**Comment by onox** [comment]
I have renamed the section "Computer Graphics" to "Graphics and Multimedia".

**Comment by onox** [comment]
@mgrojo You can rebase your commit on the latest commit in ohenley/awesome-ada and then amend it after moving your item to the "Graphics and Multimedia" section.

**Comment by ohenley** [comment]
@mgrojo Yeah, the new Graphics and Multimedia would be the proper section. 

Also, it should read [asfml] ... lower case. I enforce this casing to give uniformity to the list, else it would end up as a 'people prefered casing pizza'. (tried and seen on other lists, it looks just wrong ... for my curating). :)

Thx for the contribution!

**Comment by mgrojo** [comment]
I've amended the commit as suggested.

**Pull request merged**
