### PR TITLE
Add main heading and new badge

### PR DESCRIPTION
**Pull request by mgrojo**
This will remove this awesome-lint error:

```
README.md:1:1:   Missing main list heading                                    remark-lint:awesome-heading
```

Added as required by
https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list

See issue #107

### CODE REVIEW

**Comment by onox** [comment]
Does this PR fix multiple issues?  I see you have replaced some Markdown like `[name-of-url]` with `[name](url)`, but kept the url defined somewhere else. Is the linter complaining about constructs like `[name]`? Have you tried `[name][name-of-url]`?

**Comment by mgrojo** [comment]
Indeed. It's fixing two issues, and I was not aware of that. Sorry, I thought I had already pushed the change about the links; but it might require review after all.

The linter is complaining about `[name]` references when present in a list item with this kind of errors:
```
  ✖  319:3    Invalid list item link                                       remark-lint:awesome-list-item
  ✖  338:3    Invalid list item link                                       remark-lint:awesome-list-item
  ✖  341:3    Invalid list item link                                       remark-lint:awesome-list-item
```
I was the one introducing this kind of references to avoid repeating URLs (when they are mentioned in another part of the file) and improve readability, but it seems to go against the awesome guidelines. So I removed this kind of links when not reused and kept them when reused. In the latter case, I kept the separate link (`[name]: url`) and added the embedded link (`- [name](url)`) to satisfy the linter. Do you think I should redo this pull request and separate the changes in two?

**Comment by onox** [comment]
> Do you think I should redo this pull request and separate the changes in two?

That would be better if it's not too much work for you.

> to satisfy the linter. 

Does `[name][name]` not satisfy the linter as well? Then you can still avoid repeating URLs, which was nice.

**Comment by mgrojo** [comment]
> > Do you think I should redo this pull request and separate the changes in two?
> 
> That would be better if it's not too much work for you.
> 
> > to satisfy the linter.
> 
> Does `[name][name]` not satisfy the linter as well? Then you can still avoid repeating URLs, which was nice.

Do you mean like this?
```
- [gtkada][gtkada] - Ada graphical toolkit based on Gtk3 components.
- [qt-ada](https://r3fowwcolhrzycn2yzlzzw.on.drv.tw/AdaStudio/qt6ada/qt6ada.html) - Ada-2012 port to Qt 6 framework.
...
[gnoga]: https://sourceforge.net/projects/gnoga/
[gtkada]: https://github.com/AdaCore/gtkada
```
It still complains, and doesn't like repeating `[name]` either.
```
README.md:344:3:   Remove the link label as it matches the reference text       remark-lint:no-unneeded-full-reference-link
README.md:344:3:   Invalid list item link                                       remark-lint:awesome-list-item
```
Maybe the linter is a bit pedantic in not accepting `- [name] - Name is...`?

I've opened  #111 for these changes.

**Comment by onox** [comment]
Looks like a bug in the linter then. But you can still make the linter happy by prefixing the url ref with a short hardcoded string like "url-" so that you get something like `[NAME][url-NAME]` and `[url-NAME]: URL`.

**Comment by mgrojo** [comment]
> Looks like a bug in the linter then. But you can still make the linter happy by prefixing the url ref with a short hardcoded string like "url-" so that you get something like `[NAME][url-NAME]` and `[url-NAME]: URL`.

That would work around "Remove the link label as it matches the reference text" but would still raise "Invalid list item link". Anything different to `[name](url)`in list entries raises the error.

**Comment by onox** [comment]
That's unfortunate. Perhaps open an issue on the linter's project page? What I wrote should be valid Markdown.

**Comment by mgrojo** [comment]
Ok. See https://github.com/sindresorhus/awesome-lint/issues/161

**Pull request merged**
