### PR TITLE
Removed the Matrix room

### PR DESCRIPTION
**Pull request by thindil**
As Gitter was merged with Matrix, we probably don't need two rooms there :smile:

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Gitter speaks Matrix, but the name has not changed.
Did they announce that Gitter will be renamed?

**Comment by thindil** [comment]
@Fabien-Chouteau: As far I understand this: https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix yes, the plan is completely merge Gitter and left it as another Matrix server. Or I wrong understood it?

**Comment by Fabien-Chouteau** [comment]
I see nothing in there that says Gitter will go away or be renamed Matrix any time soon.

**Comment by thindil** [comment]
I found it in this link above plus in https://matrix.org/blog/2020/12/07/gitter-now-speaks-matrix

> In the medium/long term, it’s simply not going to be efficient for the combined Element/Gitter team to split our efforts maintaining two high-profile Matrix clients. Our plan is instead to merge Gitter’s features into Element (or next generations of Element) itself and then - if and only if Element has achieved parity with Gitter - we expect to upgrade the deployment on gitter.im to a Gitter-customised version of Element. The inevitable side-effect is that we’ll be adding new features to Element rather than Gitter going forwards.

But as I wrote, I could wrong understand it. Thus, I can create a new pull request with only removed Matrix room. At least this one is 100% sure, we discussed it there :smile:

**Comment by ohenley** [comment]
Ok, let's wait for things to be a reality. In due time we can amend this PR to reflect whatever will happen.
I will let it open until then.

**Comment by thindil** [comment]
I think it will be better to split it: delete this and remove only old Matrix room. At least repo history will be cleaner :smile:

**Comment by onox** [comment]
@thindil Are you deprecating the #ada-lang room at matrix.org? If yes, the matrix-ada link could be updated to https://matrix.to/#/#ada-lang_Lobby:gitter.im (I don't know if this url will work since I don't use Matrix) instead of removing it.

**Comment by thindil** [comment]
@onox Not exactly deprecating or removing, we decided to change it profile to home for our RSS bot (basically it sends RSS feed from Ada Planet to the room). I need to contact with someone who is admin in existing Ada community on Gitter and add this room in that same way as others Ada related rooms are added grouped there.

About the link: interesting idea, just as usual I have to be cranky :smile: When Matrix will finish work on Gitter it will be literally the alias of the old Gitter room (if it will not be that same link). Thus, probably soon or later it will have to be removed too. But again, any thoughts on this?

**Comment by onox** [comment]
Closing this PR since the link has been changed in 2428b8f to point to the Lobby channel on Gitter.

**Comment by onox** [comment]
Moved link to News and Resources section in 81485b5.

**Pull request closed without merging**
