### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andreacervetti**
Hello! I added a game (buttons) i wrote in Ada. I hope it can be interesting.

### CODE REVIEW

**Comment by ohenley** [comment]
It would be cool if you could add a screenshot of your game in the github repo readme.
Thx.

**Comment by andreacervetti** [comment]
Il giorno ven 24 mag 2019 alle ore 21:41 ohenley <notifications@github.com>
ha scritto:

> It would be cool if you could add a screenshot of your game in the github
> repo readme.
> Thx.
>
>
> Thanks for your suggestion.
The problem is that, to be honest, I don't know how to do this on github.
I mean, I know how to add a link to a screenshot in readme, but I don't
know where to put the file without having to add it to the source files.
Do you have any tip?
Thx.

A.Cervetti

**Comment by ohenley** [comment]
There is many ways... ask google. Here is one:

https://ardalis.com/add-images-easily-to-github

Take care,

Olivier

**Comment by andreacervetti** [comment]
Done.

Thanks.

A.

**Pull request merged**
