### PR TITLE
Added thumbnails to 10 projects

### PR DESCRIPTION
**Pull request by zertovitch**

### CODE REVIEW

**Comment by thindil** [comment]
I'm afraid I'm against this one change. It almost completely broke how the list look. 😞 I think, images as headers on the top or between sections are ok. But as far I remember, images, especially **before** elements of the lists, are not allowed in awesome lists. Elements of the list can contain only characters and eventually badges.

Here is the reference for the awesome list format:
https://github.com/sindresorhus/awesome/blob/f76c1cebad4ab84ad39b55e450ca1619d93349d8/pull_request_template.md

**Comment by ohenley** [comment]
@thindil I agree.

@zertovitch I love your work and I think it should be better known, shared, etc. Nevertheless, I carefully added images to:
1) books, because they are major entry points for newcomers.
2) competitions because they are major happenings.
3) Gnat Studio because it is a major entry point for newcomers.

As long as any one of your projects does become a "must-have" for starting one Ada journey, I will vote to not add an image of the project. It's a curating decision/vote. If I say yes to your projects, many will want to add a visual of their project and the list will break as a whole, format speaking. Nevertheless, presenting images and extensive readmes on your git repo is a must and will drive interest. Feel free to discuss. Thanks mate.

**Comment by zertovitch** [comment]
@thindil, @ohenley: I understand your point(s).

**Comment by thindil** [comment]
@zertovitch thank you for your understanding, and I'm sorry for wasting your time. 

If I remember correctly, we had a discussion about images on the list, but it is hidden somewhere in pull requests. 😉 I’m not surprised that information is well hidden.
Maybe we should add here some information about the list's format? For example, in the Wiki or to the pull request template?

**Comment by zertovitch** [comment]
No problem about the wasted time. I wanted to see if the thumbnails (prepared long time ago for the list) were of any use. What is the proper way of getting rid of the pull request? Should I close it on my side?

**Comment by thindil** [comment]
Probably the best way is to just close request. It will not be added then. If something will be wrong, scream on me. 😄

**Pull request closed without merging**
