### PR TITLE
Added Ada 2022 Reference Card

### PR DESCRIPTION
**Pull request by bracke**

### CODE REVIEW

**Comment by mgrojo** [comment]
I'd put it in the [Reference section](https://github.com/ohenley/awesome-ada?tab=readme-ov-file#reference).

**Comment by mgrojo** [comment]
Sorry, @bracke, I don't follow you. Do you mean the Docs link in the GitHub footer?

I mean that you have placed the link to the reference card in the [Education > Online Books](https://github.com/ohenley/awesome-ada?tab=readme-ov-file#online-books) section of the list. I think the card should be listed in the [Education > Reference](https://github.com/ohenley/awesome-ada?tab=readme-ov-file#reference) section, instead.

**Comment by bracke** [comment]
@mgrojo  Ah, sorry I misunderstood.

I agree the location you mention makes sense.
Can You change it?

**Comment by mgrojo** [comment]
Moved to Reference and merge. Thanks!

**Pull request merged**
