### PR TITLE
Add AdaML

### PR DESCRIPTION
**Pull request by rocher**
This is a small toll I've just released to draw Ada-tailored UML diagrams with specific emphasis in Ada characteristics.
Couldn't found anything referring UML, so I'm not quite sure if the location of the AdaML entry in the README.md file is the most appropriate one.

### CODE REVIEW

**Comment by ohenley** [comment]
Hi rocher,

I read your readme.md and fail to understand what it makes if it does not
"generate Ada code" and does not "draw UML diagrams from Ada code".

I think it would help to have and example in your readme of what it takes in input and what it produces.

Also, there is already a 'generator' section in this awesome list . Should it go there?

Again, has I fail to properly grasp what this project is really about, its hard for me to move on with this PR.

Give me news,

olivier

**Comment by rocher** [comment]
Hi Olivier,

There is an example in the README.md file, more or less at the end  (that with Pan_Dimensional and Deep_Thought classes). Anyway, I've added another one at the beginning that tries to self-explain AdaML. I've included both the diagram and the source code. Hope that helps (I plan to make a gallery of examples to help users create their own diagrams, but still under development). Also, I'll force PlantUML proxy to use a cache in case diagrams take too long to show up in the README.md.

Regarding the place of the AdaML entry in your README.md, once you get the idead of what AdaML is for, please choose yourself the most appropriate one in case you don't like where I put it.

Please let me know what you think now, with the new changes I've made...

BR,
Francesc Rocher

**Comment by ohenley** [comment]
Hi rocher,

Thanks for the amendments. Your new readme.md is great! Now I get it.

**Comment by rocher** [comment]
Hi Olivier

Thanks for accepting this entry!!

**Pull request merged**
